# Generated by Django 3.1.6 on 2021-02-17 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ifsc', models.CharField(max_length=250)),
                ('branch', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=250)),
                ('district', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=250)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_branches', to='banks.bank')),
            ],
        ),
    ]
